### ISSUE TITLE
GeomFunc todo &  tidy-up

### ISSUE THREAD

**Issue by phockett** [phockett/ePSproc#26]
Basics now working.  Some outstanding todo items:

- [ ] E-field methods to add.
- [ ] Sph fns. (Use existing, try SHtools, consolidate.) Note current issue with BLM dim labels (L,M or l,m in old fns.)
- [ ] Time-dependent calcs & plotting.

**Comment by phockett** [comment]
Need to check Euler/RX coord handling and sub-selection. Seem to be issues here with QN assignment and wignerD routine, likely due to both assumptions about data array.

Tested quick fixes by mods to sphCalc.wDcalc() function, but not yet working, and may not be the best way to handle this in any case!

**Comment by phockett** [comment]
Fixed accidental pol geometry issue with AF calcs - due to this option remaining in AF code from MF code conversion/base functions. 

By definition, there is no frame rotation in the AF case! For cases where E-field and alignment distribution are rotated, set AKQS in rotated frame (not yet tested).

See 5b5fbcf7c931e4205787d089468488ffc81c7944

**Comment by phockett** [comment]
**Xarray version issues in geom code**

Testing on Jake/Ubuntu20 today, some new issues... Note this is currently an issue on Jake only, maybe other env/dependencies problem 

- v0.17 breaks in-place assignments (on Linux only, possibly)? E.g. `da['mu'] = -1 * da['mu']` is OK, but `da['mu'] *= -1` no longer working (was OK for v0.15). 
- Quick test with v0.19 gives other issues to - to be addressed - and v0.15 also not working (although was [previously OK, at least on Win](https://epsproc.readthedocs.io/en/dev/demos/ePSproc_class_demo_161020.html)). 
- v0.13 is working in same env., 
- All tested via `conda install xarray=XX`, and each env backed up for reference.

**Comment by phockett** [comment]
**Xarray and Python version issues** 

Fixed in https://github.com/phockett/ePSproc/pull/51

**Comment by phockett** [comment]
**Testing for 3D alignment/AFPAD case July 2023**

- Dev branch https://github.com/phockett/ePSproc/tree/3d-AFPAD-dev
- 79abfeb36e64a5d5b3914e0346087450c0f3e13d implements phase fixes, this gives correct M!=0 terms for ePS matrix elements in testing with OCS and C2H4 cases. Fix here was setting `phaseCons['afblmCons']['negM'] = not(phaseCons['genMatEcons']['negm'])`, although it's possible this introduces inconsistencies elsewhere.
- 6a178689b7252f5ebf4b33eb4a49cf6e4794fd88 allows for `phaseCons['afblmCons']` for different cases. For `S` case, note that fix above removes `M!=0` terms from DeltaTerm. This is incorrect!!!! And may also be incorrect above... TBC.

NOTE: this version used for  QM3 book builds, corresponding archive at https://github.com/phockett/ePSproc/releases/tag/v1.3.2-dev-3d-QM3-310723

**Comment by phockett** [comment]
**Polarization states and pol geoms Feb/March 2024**

- Dev on current 3d branch, https://github.com/phockett/ePSproc/tree/3d-AFPAD-dev
- Basics in place (e914b1691952a4ded56ceb5b667510e391efc62d, intro docs https://epsproc.readthedocs.io/en/3d-afpad-dev/demos/Epol_class_demo_docs_030324.html), but note some odd Blms in some cases in testing, maybe related to phase issues above, particularly for degen states and/or cases where the cross-section is small.
- TODO: more careful testing, and docs for pol geoms generally.

UPDATE 14/03/24: Basics in place, including docs and testing, as of f126bbba37c6f151319ffc320ce9acfc27e9596c
